"""Contains a list of words for parser"""

STOP_WORDS = ['a', 'abord', 'absolument', 'adresse', 'afin', 'ah', 'ai', 'aie', 'ailleurs', 'ainsi', 'ait', 'allez',
              'allo', 'allons', 'alors', 'anterieur', 'anterieure', 'anterieures', 'apres', 'as', 'assez', 'attendu',
              'au', 'aucun', 'aucune', 'aujourd', "aujourd'hui", 'aupres', 'auquel', 'aura', 'auraient', 'aurait',
              'auront', 'aussi', 'autre', 'autrefois', 'autrement', 'autres', 'autrui', 'aux', 'auxquelles', 'auxquels',
              'avaient', 'avais', 'avait', 'avance', 'avant', 'avec', 'avoir', 'avons', 'ayant', 'b', 'bah', 'bas',
              'basee', 'bat', 'beau', 'beaucoup', 'belle', 'bien', 'bigre', 'bonjour', 'bonsoir', 'boum', 'bravo',
              'brrr', 'c', 'ca', 'car', 'ce', 'ceci', 'cela', 'celle', 'celle-ci', 'celle-la', 'celles', 'celles-ci',
              'celles-la', 'celui', 'celui-ci', 'celui-la', 'cent', 'cependant', 'certain', 'certaine', 'certaines',
              'certains', 'certes', 'ces', 'cet', 'cette', 'ceux', 'ceux-ci', 'ceux-la', 'chacun', 'chacune', 'chaque',
              'cher', 'chere', 'cheres', 'chers', 'chez', 'chiche', 'chut', 'ci', 'cinq', 'cinquantaine', 'cinquante',
              'cinquantieme', 'cinquieme', 'clac', 'clic', 'combien', 'comme', 'comment', 'comparable', 'comparables',
              'compris', 'concernant', 'connais', 'connait', 'connaitrais', 'connaitre', 'contre', 'couic', 'crac', 'd',
              'da', 'dans', 'de', 'debout', 'dedans', 'dehors', 'deja', 'dela', 'depuis', 'dernier', 'derniere',
              'derriere', 'des', 'desormais', 'desquelles', 'desquels', 'dessous', 'dessus', 'deux', 'deuxieme',
              'deuxiemement', 'devant', 'devers', 'devra', 'different', 'differente', 'differentes', 'differents',
              'dire', 'directe', 'directement', 'dit', 'dite', 'dits', 'divers', 'diverse', 'diverses', 'dix',
              'dix-huit', 'dix-neuf', 'dix-sept', 'dixieme', 'doit', 'doivent', 'donc', 'dont', 'douze', 'douzieme',
              'dring', 'du', 'duquel', 'durant', 'e', 'effet', 'egale', 'egalement', 'egales', 'eh', 'elle',
              'elle-meme', 'elles', 'elles-memes', 'en', 'encore', 'enfin', 'entre', 'envers', 'environ', 'es',
              'espere', 'est', 'et', 'etaient', 'etais', 'etait', 'etant', 'etc', 'ete', 'etre', 'eu', 'euh', 'eux',
              'eux-memes', 'exactement', 'excepte', 'extenso', 'exterieur', 'f', 'facon', 'fais', 'faisaient',
              'faisant', 'fait', 'feront', 'fi', 'flac', 'floc', 'font', 'g', 'gens', 'grandma', 'grandpy', 'granpa',
              'h', 'ha', 'he', 'hein', 'helas', 'hem', 'hep', 'hi', 'hier', 'ho', 'hola', 'hop', 'hormis', 'hors',
              'hou', 'houp', 'hue', 'hui', 'huit', 'huitieme', 'hum', 'hurrah', 'i', 'il', 'ils', 'importe', 'indique',
              'indiquer', 'indiques', 'j', 'je', 'jusqu', 'jusque', 'juste', 'k', 'l', 'la', 'laisser', 'laquelle',
              'las', 'le', 'lequel', 'les', 'lesquelles', 'lesquels', 'leur', 'leurs', 'longtemps', 'lors', 'lorsque',
              'lui', 'lui-meme', 'm', 'ma', 'maint', 'maintenant', 'mais', 'malgre', 'mamie', 'maximale', 'me', 'meme',
              'memes', 'merci', 'mes', 'mien', 'mienne', 'miennes', 'miens', 'mille', 'mince', 'minimale', 'moi',
              'moi-meme', 'moindres', 'moins', 'mon', 'moyennant', 'multiple', 'multiples', 'n', 'na', 'naturel',
              'naturelle', 'naturelles', 'ne', 'neanmoins', 'necessaire', 'necessairement', 'neuf', 'neuvieme', 'ni',
              'nombreuses', 'nombreux', 'non', 'nos', 'notamment', 'notre', 'notres', 'nous', 'nous-memes', 'nouveau',
              'nul', 'o', 'oh', 'ohe', 'ole', 'olle', 'on', 'ont', 'onze', 'onzieme', 'ore', 'ou', 'ouf', 'ouias',
              'oust', 'ouste', 'outre', 'ouvert', 'ouverte', 'ouverts', 'o|', 'p', 'paf', 'pan', 'papi', 'papibot',
              'papy', 'papybot', 'par', 'parce', 'parfois', 'parle', 'parlent', 'parler', 'parmi', 'parseme', 'partant',
              'particulier', 'particuliere', 'particulierement', 'pas', 'passe', 'pendant', 'pense', 'permet',
              'personne', 'peu', 'peut', 'peuvent', 'peux', 'pff', 'pfft', 'pfut', 'pif', 'pire', 'plait', 'plein',
              'plouf', 'plus', 'plusieurs', 'plutot', 'possessif', 'possessifs', 'possible', 'possibles', 'pouah',
              'pour', 'pourquoi', 'pourrais', 'pourrait', 'pouvait', 'prealable', 'precisement', 'premier', 'premiere',
              'premierement', 'pres', 'probable', 'probante', 'procedant', 'proche', 'psitt', 'pu', 'puis', 'puisque',
              'pur', 'pure', 'q', 'qu', 'quand', 'quant', 'quant-a-soi', 'quanta', 'quarante', 'quatorze', 'quatre',
              'quatre-vingt', 'quatrieme', 'quatriemement', 'que', 'quel', 'quelconque', 'quelle', 'quelles',
              "quelqu'un", 'quelque', 'quelques', 'quels', 'qui', 'quiconque', 'quinze', 'quoi', 'quoique', 'r', 'rare',
              'rarement', 'rares', 'relative', 'relativement', 'remarquable', 'rend', 'rendre', 'restant', 'reste',
              'restent', 'restrictif', 'retour', 'revoici', 'revoila', 'rien', 's', 'sa', 'sacrebleu', 'sais', 'sait',
              'salut', 'salutations', 'sans', 'sapristi', 'sauf', 'saurai', 'saurais', 'saurait', 'savoir', 'se',
              'sein', 'seize', 'selon', 'semaine', 'semblable', 'semblaient', 'semble', 'semblent', 'sent', 'sept',
              'septieme', 'sera', 'seraient', 'serait', 'seront', 'ses', 'seul', 'seule', 'seulement', 'si', 'sien',
              'sienne', 'siennes', 'siens', 'sinon', 'six', 'sixieme', 'soi', 'soi-meme', 'soir', 'soiree', 'soit',
              'soixante', 'son', 'sont', 'sous', 'souvent', 'specifique', 'specifiques', 'speculatif', 'stop', 'script',
              'strictement', 'subtiles', 'suffisant', 'suffisante', 'suffit', 'suis', 'suit', 'suivant', 'suivante',
              'suivantes', 'suivants', 'suivre', 'superpose', 'sur', 'surtout', 't', 'ta', 'tac', 'tant', 'tardive',
              'te', 'tel', 'telle', 'tellement', 'telles', 'tels', 'tenant', 'tend', 'tenir', 'tente', 'tes', 'tic',
              'tien', 'tienne', 'tiennes', 'tiens', 'toc', 'toi', 'toi-meme', 'ton', 'touchant', 'toujours', 'tous',
              'tout', 'toute', 'toutefois', 'toutes', 'treize', 'trente', 'tres', 'trois', 'troisieme', 'trouvent',
              'trop', 'trouve', 'tsoin', 'tsouin', 'tu', 'u', 'un', 'une', 'unes', 'uniformement', 'unique', 'uniques',
              'uns', 'v', 'va', 'vais', 'vas', 've', 'vers', 'veut', 'via', 'vif', 'vifs', 'vingt', 'vivat', 'vive',
              'vives', 'vlan', 'voici', 'voila', 'vont', 'vos', 'votre', 'votres', 'voudrais', 'voudrait', 'vous',
              'vous-memes', 'vu', 'w', 'x', 'y', 'z', 'zut']
